# First check if all the things in the generator are needed; 
# if so, just fork the original and add my little things

"""
Generates a gcode file to set your 3D printer's bed or enclosure temperature to a
fixed temperature for a set amount of time in order to dry spools of filament.
"""

from datetime import datetime

__author__ = """Kestin Goforth"""
__email__ = "kgoforth1503@gmail.com"
__version__ = "0.2.2"
__copyright__ = "Copyright 2022"
__license__ = "AGPLv3"
__scriptname__ = "Filament Dryer Gcode Script Generator"
__url__ = "https://github.com/Team-7159-RoboRavens/Filament-Dryer-GCode-Scripts"

CHIRPS = (
    (60, 100),  # 60Hz 100ms
    (60, 125),  # 60Hz 100ms
    (60, 150),  # 60Hz 100ms
)

DEFAULT_COMMANDS = {
    "bed_set": "M140 S%d; Set target bed temperature",
    "chamber_set": "M141 S%d; Set target chamber temperature",
    "bed_wait": "M190 S%d; Wait for target bed temperature",
    "chamber_wait": "M191 S%d; Wait for target chamber temperfature",
    "dwell": "G4 S%d",
    "chirp": "M300 S%d P%d ; Chirp",
    "message": "M117 %s",
    "progress": "M73 P%d R%d",
    "reset": "M502",
    "lights on": "M601 S255",
    "fans": "M106 P%d S%d",
}

def create_file(filename, time, temperature, use_bed, use_chamber, evo):
    """
    Generates a gcode file to set your 3D printer's bed or enclosure temperature to a
    fixed temperature for a set amount of time in order to dry spools of filament.

    Args:
        filename (str): Output filename.
        time (int): Drying time, in minutes.
        temperature (int): Drying temperature, in degrees Celsius.
        use_bed (bool, optional): Use the bed heater. Defaults to False.
        use_chamber (bool, optional): Use the chamber heater. Defaults to False.
    """
    with open(filename, "wb+") as handle:
        _ = create_script(handle, time, temperature, use_bed, use_chamber, evo)


def create_script(
    handle,
    time,
    temperature,
    use_bed=False,
    use_chamber=False,
    evo=False,
    encoding="utf-8",
    newline="\n",
    cmds=DEFAULT_COMMANDS
):
    """
    Writes a gcode script to the provided BytesIO-like stream.

    The script sets your 3D printer's bed or enclosure temperature to a fixed
    temperature for a set amount of time in order to dry spools of filament.

    Args:
        handle (BytesIO): Output output stream handle.
        time (int): Drying time, in minutes.
        temperature (int): Drying temperature, in degrees Celsius.
        use_bed (bool, optional): Use the bed heater. Defaults to False.
        use_chamber (bool, optional): Use the chamber heater. Defaults to False.
        encoding (str, optional): Encoding for string. Defaults to encoding.

    Returns:
        handle (BytesIO): The output stream handle.
        num_bytes (int): Number of bytes written
    """
    print(f"encoding: {encoding}")
    if not use_chamber and not use_bed:
        raise Exception("Must enable either bed or chamber.")

    num_bytes = 0

    def write(*lines, newline=newline):
        text = newline.join([e for e in lines if e is not None]).encode(encoding)
        text += newline.encode(encoding)
        handle.write(text)
        return len(text)

    # Write header info
    date_str = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    num_bytes += write(
        f"; generated by [{__scriptname__}]({__url__})",
        f"; {__copyright__}  {__author__}",
        f"; version: {__version__}, date: {date_str}",
        "; ".join(  # comment for human reading here
            (
                "",
                f"temp: {temperature:d} C",
                f"time: {time:d} mins",
                f"use_bed: {use_bed!r}",
                f"use_chamber: {use_chamber!r}",
            )
        ),
        "",
    )

        # Start g-code goes here!
        # What I will do: Just copy in the contents of EvoStartCode
    if evo:
        # startFile = open("/evoCode/EvoStartCode.gcode", "r")
        # startCode = startFile.read()
        # num_bytes += write(startCode)
        # startFile = open("/evoCode/EvoStartCode.gcode", "r")
        # for line in startFile:
        #     num_bytes += write(line)
        # startFile.close()
        num_bytes += write(""";APEX 1.8.8
;EVO
;NOZZLE: PRIMARY
;SIZE: 0.8mm
;MATERIAL: ABS
;QUALITY: PRECISE
;LAYER HEIGHT: 0.22mm
;WALLS: 1mm
;FILL: 29%
;PRINT SPEED: ?print_STANDARD?mm/s
;PRINT TEMPERATURE: 238C
;INITIAL BED TEMPERATURE: 124C
;SIZE: SMALL
;PRINT TIME: 23 minutes
;FILAMENT USED: 7.0g
;DATE: 01-26-2026

;START CODE
M502                 ;Reset
M601 S255            ;Lights on
M106 P2 S5           ;Center STANDARD low for quick nozzle heating
M106 S0              ;Side fans off
;Special Bed Prep Off

;M104 T0 S238         Set nozzle 1 to temp
;M104 T1 S0           Set nozzle 2 to temp
;M140 S124            Set bed to temp
;M141 S0              Chamber Heaters Off

T0                           ; First nozzle
G21                          ; Metric values
G90                          ; Absolute positioning
M82                          ; Set extruder to absolute mode
M107                         ; Start with the fan off
G92 E0                       ; Set extruder to 0
G28                          ; Home all
G0 Z0  F1200                 ; Bring up Z

;M109 T0 S238            Hold until nozzle 1 at temp
;M109 T1 S0              Hold until nozzle 2 at temp
;M190 S124               Hold until bed at temp

M106 P2 S175            ; Turn center fan back on (STANDARD depends on filament)
M204 S2000              ; Set acceleration for auto-level sequence
G0 Z3 F900              ; Raise hot end above bed rails

T0                      ; Nozzle 1
;G1 E-15 F100             Retract filament 15mm to minimize auto-level error

G0 X0 Y350 F15000       ; Quickly move to left of brush
G0 Z0 F900              ; Lower to brush

;LEFT-RIGHT
G0 X25 Y350 F2000       ; Slowly move right across brush in zig zag
G0 X38 Y342 Z-1         ; Slowly move right across brush in zig zag
G0 X51 Y350 Z0          ; Slowly move right across brush in zig zag
G0 X64 Y342 Z-1         ; Slowly move right across brush in zig zag
G0 X77 Y350 Z0          ; Slowly move right across brush in zig zag
G0 X90 Y342 Z-1         ; Slowly move right across brush in zig zag
G0 X105 Y350 Z0         ; Slowly move right across brush in zig zag
G0 X120 Y342 Z-1        ; Slowly move right across brush in zig zag
G0 X120 Y350  Z0        ; Slowly move to the right of the brush

;RIGHT-LEFT
G0 X85 Y350 Z-1 F2000   ; Slowly move left across brush
G0 X25 Y350 Z0          ; Slowly move left across brush

;LEFT-RIGHT
G0 X38 Y342 Z-1         ; Slowly move right across brush in zig zag
G0 X51 Y350 Z0          ; Slowly move right across brush in zig zag
G0 X64 Y342 Z-1         ; Slowly move right across brush in zig zag
G0 X77 Y350 Z0          ; Slowly move right across brush in zig zag
G0 X90 Y342 Z-1         ; Slowly move right across brush in zig zag
G0 X105 Y350 Z0         ; Slowly move right across brush in zig zag
G0 X120 Y342 Z-1        ; Slowly move right across brush in zig zag
G0 X120 Y350  Z0        ; Slowly move to the right of the brush
;G1 E-20 F125            Retract more filament

;RIGHT-LEFT
G0 X85 Y350 Z-1 F2000   ; Slowly move left across brush
G0 X25 Y350 Z0          ; Slowly move left across brush

G29                     ; Auto-level
G91                     ; Relative positioning
G0 Z3 F900              ; Lift nozzle 1mm  G0 Z+ NOT recognized by GENESIS board - must use G0 Z1,2, etc. in relative mode
G90                     ; Absolute positioning
G0 X143 Y300 F15000     ; Move right across bed quickly
G0 X143 Y350 F15000     ; Move above dump tank quickly
G0 Z-2 F900             ; Lower nozzle to -2mm

T0                      ; Nozzle 1
G92 E0                  ; Clear filament counter
;G1 E24 F100              Prime filament 1 into dump tank
G92 E0                  ; Clear filament counter

G0 X220 Y350 F15000         ; Move right quickly to remove filament
G0 Z0.5 F900                ; Raise nozzle to .5mm over bed
G0 X220 Y300 F15000         ; Move to rear of bed quickly

M201 X1200 Y1200 Z100 E1000  ; Set acceleration
M906 X12 Y12 Z14          ; Set stepper current
M92 X100.5 Y100.5   ; Shrinkage compensation
M400


M104 T0 S0         ; Set nozzle 1 to temp

;end start code start drying code

G0 Z280 F1200                 ; Bring up Z
""")

    print(use_bed)
    print(use_chamber)

    print(evo)
    # this will call a different file within the repo which is good bc they pip everything

    # Set target temperatures
    num_bytes += write(
        cmds["message"] % "Heating",
        cmds["chirp"] % CHIRPS[0],
        (cmds["bed_set"] % temperature) if use_bed else None,
        (cmds["chamber_set"] % temperature) if use_chamber else None,
        (cmds["bed_wait"] % temperature) if use_bed else None,
        (cmds["chamber_wait"] % temperature) if use_chamber else None,
        cmds["chirp"] % CHIRPS[0],
        cmds["chirp"] % CHIRPS[1],
        "",
    )

    # Dwell until target time has elapsed
    total_mins = 0
    while total_mins < time:
        remaining = time - total_mins
        if remaining <= 5 or total_mins % 5 == 0:
            progress = int(100.0 * total_mins / time)
            num_bytes += write(
                cmds["progress"] % (progress, remaining),
                cmds["message"] % ("Drying: %d mins Remaining" % remaining),
            )
        num_bytes += write(cmds["dwell"] % 60)  # Wait 60 seconds
        total_mins += 1

    # Chirp and set message
    num_bytes += write(
        cmds["progress"] % (100, 0),
        cmds["message"] % "Drying Done",
        "",
        cmds["chirp"] % CHIRPS[0],
        cmds["chirp"] % CHIRPS[1],
        cmds["chirp"] % CHIRPS[2],
        (cmds["bed_set"] % 0) if use_bed else None,
        (cmds["chamber_set"] % 0) if use_chamber else None,
        "",
    )

    # End code goes here!
    if evo:
        # closeFile = open("/evoCode/EvoEndCode.gcode", "r")
        # for line in startFile:
        #   num_bytes += write(line)
        # closeFile.close()
        num_bytes += write("""M400
G28                             ; home all
M104 T0 S0                      ; switch off first nozzle
M104 T1 S0                      ; switch off second nozzle
M140 S0                         ; heated bed heater off
M141 S0                         ; chamber heaters off
M107                            ; fans off
T0
G92 E0                          ; set first extruder to 0
;G1 E-3 F300                      retract a bit to relieve pressure
T1
G92 E0                          ; set second extruder to 0
;G1 E-3 F300                      retract a bit to relieve pressure
T0								; switch back to extruder 1
M84                             ; steppers off
G90                             ; absolute positioning
;{cool_code}
;LIGHT SEQUENCE
M601 S0
G4 P500
M601 S255
G4 P500
M601 S0
G4 P1500
M601 S255
G4 P1500
M601 S0
G4 P500
M601 S255
G4 P500
M601 S0
G4 P1500
M601 S255
G4 P1500
M601 S0
G4 P500
M601 S255
G4 P500
M601 S0
G4 P500
M601 S255
G4 P500
M601 S0                         ;Turn lights off
""")

    return handle, num_bytes


def main():
    import argparse
    import os

    """
    Generates a gcode file to set your 3D printer's bed or enclosure temperature to a
    fixed temperature for a set amount of time in order to dry spools of filament.
    """

    parser = argparse.ArgumentParser(
        prog="filament_dryer_script_generator", description=__doc__
    )

    parser.add_argument("filename", type=str, help="(str) output filename")
    parser.add_argument("time", type=int, help="(int) drying time, in minutes")
    parser.add_argument(
        "temperature",
        type=int,
        help="(int) drying temperature, in degrees Celsius",
    )
    parser.add_argument(
        "--bed", action="store_true", help="use the bed heater for drying"
    )
    parser.add_argument(
        "--chamber", action="store_true", help="use the chamber heater for drying"
    )
        # --includeEvoStartEnd
    parser.add_argument(
        "--includeEvoStartEnd", action="store_true", help="include the start g-code & end g-code for the Evo3"
    )

    args = parser.parse_args()

    print("Generating Dryer Script")
    print("  File:    %s" % os.path.split(args.filename)[1])
    print("  Time:    %d mins" % args.time)
    print("  Temp:    %d deg C" % args.temperature)
    print("  Bed:     %r" % args.bed)
    print("  Chamber: %r" % args.chamber)
    print("  EvoStartEnd: %r" % args.includeEvoStartEnd)

    create_file(args.filename, args.time, args.temperature, use_bed=args.bed, use_chamber=args.chamber, evo=args.includeEvoStartEnd)

    print("Done.")


if __name__ == "__main__":
    import sys

    sys.exit(main())  # pragma: no cover
